name: character_viewer_exercise
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.3.10
  go_router: ^10.1.2
  http: ^1.1.0
  riverpod_annotation: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.1
  riverpod_lint: ^2.0.3


flutter:
  uses-material-design: true
  assets:
    - assets/images/
